### ISSUE TITLE
Installing with brew fails

### ISSUE THREAD

**Issue by jgrafton** [mschilli/go-ynabler#1]
```
% brew tap mschilli/homebrew https://github.com/mschilli/homebrew
==> Tapping mschilli/homebrew
Cloning into '/opt/homebrew/Library/Taps/mschilli/homebrew-homebrew'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 44 (delta 15), reused 39 (delta 10), pack-reused 0
Receiving objects: 100% (44/44), 4.86 KiB | 4.86 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Tapped 1 formula (16 files, 13.7KB).

% brew update
Already up-to-date.

% brew install ynabler
==> Fetching mschilli/homebrew/ynabler
==> Cloning https://github.com/mschilli/homebrew
Cloning into '/Users/jgrafton1/Library/Caches/Homebrew/ynabler--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Installing ynabler from mschilli/homebrew
==> /usr/local/bin/go build
Last 15 lines from /Users/jgrafton1/Library/Logs/Homebrew/ynabler/01.go:
2024-03-06 20:12:46 +0000

/usr/local/bin/go
build


If reporting this issue please do so to (not Homebrew/brew or Homebrew/homebrew-core):
  mschilli/homebrew

/opt/homebrew/Library/Homebrew/utils/github/api.rb:356:in `raise_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::API::ValidationFailedError)
        from /opt/homebrew/Library/Homebrew/utils/github/api.rb:272:in `open_rest'
        from /opt/homebrew/Library/Homebrew/utils/github.rb:178:in `search'
        from /opt/homebrew/Library/Homebrew/utils/github.rb:182:in `search_results_items'
        from /opt/homebrew/Library/Homebrew/utils/github.rb:36:in `search_issues'
        from /opt/homebrew/Library/Homebrew/utils/github.rb:62:in `issues_for_formula'
        from /opt/homebrew/Library/Homebrew/exceptions.rb:482:in `fetch_issues'
        from /opt/homebrew/Library/Homebrew/exceptions.rb:477:in `issues'
        from /opt/homebrew/Library/Homebrew/exceptions.rb:533:in `dump'
        from /opt/homebrew/Library/Homebrew/brew.rb:143:in `rescue in <main>'
        from /opt/homebrew/Library/Homebrew/brew.rb:131:in `<main>'
/opt/homebrew/Library/Homebrew/formula.rb:2840:in `block in system': Failed executing: /usr/local/bin/go build (BuildError)
        from /opt/homebrew/Library/Homebrew/formula.rb:2776:in `open'
        from /opt/homebrew/Library/Homebrew/formula.rb:2776:in `system'
        from /opt/homebrew/Library/Taps/mschilli/homebrew-homebrew/Formula/ynabler.rb:12:in `block in install'
        from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:139:in `chdir'
        from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:139:in `cd'
        from /opt/homebrew/Library/Taps/mschilli/homebrew-homebrew/Formula/ynabler.rb:11:in `install'
        from /opt/homebrew/Library/Homebrew/build.rb:177:in `block (3 levels) in install'
        from /opt/homebrew/Library/Homebrew/extend/kernel.rb:493:in `with_env'
        from /opt/homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
        from /opt/homebrew/Library/Homebrew/formula.rb:1418:in `block in brew'
        from /opt/homebrew/Library/Homebrew/formula.rb:3008:in `block (2 levels) in stage'
        from /opt/homebrew/Library/Homebrew/extend/kernel.rb:493:in `with_env'
        from /opt/homebrew/Library/Homebrew/formula.rb:3007:in `block in stage'
        from /opt/homebrew/Library/Homebrew/resource.rb:129:in `block (2 levels) in unpack'
        from /opt/homebrew/Library/Homebrew/download_strategy.rb:121:in `chdir'
        from /opt/homebrew/Library/Homebrew/download_strategy.rb:113:in `stage'
        from /opt/homebrew/Library/Homebrew/resource.rb:125:in `block in unpack'
        from /opt/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
        from /opt/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
        from /opt/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
        from /opt/homebrew/Library/Homebrew/resource.rb:226:in `stage_resource'
        from /opt/homebrew/Library/Homebrew/resource.rb:124:in `unpack'
        from /opt/homebrew/Library/Homebrew/resource.rb:98:in `stage'
        from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/forwardable.rb:238:in `stage'
        from /opt/homebrew/Library/Homebrew/formula.rb:2987:in `stage'
        from /opt/homebrew/Library/Homebrew/formula.rb:1411:in `brew'
        from /opt/homebrew/Library/Homebrew/build.rb:133:in `block in install'
        from /opt/homebrew/Library/Homebrew/extend/kernel.rb:493:in `with_env'
        from /opt/homebrew/Library/Homebrew/build.rb:125:in `install'
        from /opt/homebrew/Library/Homebrew/build.rb:229:in `<main>'
```

**Comment by mschilli** [comment]
Thanks for the report! Not 100% what exactly it is complaining about, but I've changed to formula to depend on "go" and to use "go" without the full path for the build, can you give it another try with "brew reinstall ynabler" please?

**Comment by jgrafton** [comment]
That fixed it.  I installed go with brew and it's path is /opt/homebrew/bin/go

**Comment by mschilli** [comment]
Huzzah! Thanks for letting me know.
